/**
 * @file settings.c
 * @brief Loads Smart RTU configuration from smart_rtu_config.json.
 *
 * Reads the JSON configuration generated by the Smart RTU Tool and
 * populates the global AppSettings structure used throughout the
 * application.
 */

#include "settings.h"
#include "json.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

AppSettings cfg;

/*------------------------------------------------------------*/
/**
 * @brief Load default configuration values.
 *
 * These values are used whenever a field is missing from the
 * JSON configuration file.
 */
/*------------------------------------------------------------*/
void settings_defaults(void)
{
    /* Device */

    strcpy(cfg.device_id, "AMSET-001");

    /* Modbus RTU */

    strcpy(cfg.modbus_port, MODBUS_PORT_DEF);
    cfg.modbus_baud = MODBUS_BAUD_DEF;
    cfg.modbus_slave = MODBUS_SLAVE_DEF;
    strcpy(cfg.modbus_parity, MODBUS_PARITY_DEF);
    cfg.modbus_stop_bits = MODBUS_STOPBITS_DEF;

    /* Modbus TCP */

    cfg.modbus_tcp_enable = MODBUS_TCP_ENABLE_DEF;
    strcpy(cfg.modbus_tcp_ip, MODBUS_TCP_IP_DEF);
    cfg.modbus_tcp_port = MODBUS_TCP_PORT_DEF;
    cfg.modbus_tcp_slave_id = MODBUS_TCP_SLAVE_DEF;

    /* MQTT (AWS IoT Core) */

    strcpy(cfg.mqtt_broker, MQTT_BROKER_DEF);
    cfg.mqtt_port = MQTT_PORT_DEF;
    strcpy(cfg.mqtt_client_id, MQTT_CLIENT_ID_DEF);
    strcpy(cfg.mqtt_ca_cert, MQTT_CA_CERT_DEF);
    strcpy(cfg.mqtt_device_cert, MQTT_DEVICE_CERT_DEF);
    strcpy(cfg.mqtt_private_key, MQTT_PRIVATE_KEY_DEF);
    strcpy(cfg.mqtt_topic, MQTT_TOPIC_DEF);

    /* Scan interval */

    cfg.interval = INTERVAL_DEF;

    /* WiFi */

    cfg.wifi_enable = WIFI_ENABLE_DEF;
    strcpy(cfg.wifi_ssid, WIFI_SSID_DEF);
    strcpy(cfg.wifi_password, WIFI_PASSWORD_DEF);
    strcpy(cfg.wifi_country, WIFI_COUNTRY_DEF);

    /* OTA */

    cfg.ota_enable = OTA_ENABLE_DEF;
    snprintf(cfg.ota_app_topic, sizeof(cfg.ota_app_topic),
             OTA_APP_TOPIC_DEF, cfg.device_id);
    snprintf(cfg.ota_system_topic, sizeof(cfg.ota_system_topic),
             OTA_SYSTEM_TOPIC_DEF, cfg.device_id);
    snprintf(cfg.ota_status_topic, sizeof(cfg.ota_status_topic),
             OTA_STATUS_TOPIC_DEF, cfg.device_id);
    strcpy(cfg.ota_download_dir, OTA_DOWNLOAD_DIR_DEF);
    strcpy(cfg.app_version, APP_VERSION_DEF);
    strcpy(cfg.app_binary_path, APP_BINARY_PATH_DEF);
}

/*------------------------------------------------------------*/
/**
 * @brief Load settings from Smart RTU JSON file.
 *
 * Reads:
 *   - device
 *   - wifi
 *   - mqtt
 *   - modbus_tcp
 *
 * Missing fields retain their default values.
 *
 * @return 0 on success
 * @return -1 if JSON file cannot be opened
 */
/*------------------------------------------------------------*/
int settings_load(void)
{
    settings_defaults();

    char *json = read_file(SETTINGS_FILE);

    if (json == NULL)
    {
        printf("[SETTINGS] %s not found. Using defaults.\n",
               SETTINGS_FILE);
        return -1;
    }

    /*------------------------------------------------------*/
    /* Device                                                */
    /*------------------------------------------------------*/

    char *device = strstr(json, "\"device\"");

    if (device)
    {
        json_get_string(device,
                        "device_id",
                        cfg.device_id,
                        sizeof(cfg.device_id));

        json_get_int(device,
                     "slave_id",
                     &cfg.modbus_slave);

        json_get_int(device,
                     "baud",
                     &cfg.modbus_baud);

        json_get_int(device,
                     "interval_sec",
                     &cfg.interval);

        json_get_string(device,
                        "parity",
                        cfg.modbus_parity,
                        sizeof(cfg.modbus_parity));

        json_get_int(device,
                     "stop_bits",
                     &cfg.modbus_stop_bits);
    }

    /*------------------------------------------------------*/
    /* WiFi                                                  */
    /*------------------------------------------------------*/

    char *wifi = strstr(json, "\"wifi\"");

    if (wifi)
    {
        json_get_string(wifi,
                        "ssid",
                        cfg.wifi_ssid,
                        sizeof(cfg.wifi_ssid));

        json_get_string(wifi,
                        "password",
                        cfg.wifi_password,
                        sizeof(cfg.wifi_password));

        json_get_string(wifi,
                        "country",
                        cfg.wifi_country,
                        sizeof(cfg.wifi_country));

        json_get_int(wifi,
                     "enable",
                     &cfg.wifi_enable);
    }

    /*------------------------------------------------------*/
    /* MQTT (AWS IoT Core)                                   */
    /*------------------------------------------------------*/

    char *mqtt = strstr(json, "\"mqtt\"");

    if (mqtt)
    {
        json_get_string(mqtt,
                        "broker",
                        cfg.mqtt_broker,
                        sizeof(cfg.mqtt_broker));

        json_get_int(mqtt,
                     "port",
                     &cfg.mqtt_port);

        json_get_string(mqtt,
                        "client_id",
                        cfg.mqtt_client_id,
                        sizeof(cfg.mqtt_client_id));

        json_get_string(mqtt,
                        "ca_cert",
                        cfg.mqtt_ca_cert,
                        sizeof(cfg.mqtt_ca_cert));

        json_get_string(mqtt,
                        "device_cert",
                        cfg.mqtt_device_cert,
                        sizeof(cfg.mqtt_device_cert));

        json_get_string(mqtt,
                        "private_key",
                        cfg.mqtt_private_key,
                        sizeof(cfg.mqtt_private_key));

        json_get_string(mqtt,
                        "topic",
                        cfg.mqtt_topic,
                        sizeof(cfg.mqtt_topic));
    }

    /*------------------------------------------------------*/
    /* Modbus TCP                                            */
    /*------------------------------------------------------*/

    char *mbtcp = strstr(json, "\"modbus_tcp\"");

    if (mbtcp)
    {
        json_get_int(mbtcp,
                     "enable",
                     &cfg.modbus_tcp_enable);

        json_get_string(mbtcp,
                        "ip",
                        cfg.modbus_tcp_ip,
                        sizeof(cfg.modbus_tcp_ip));

        json_get_int(mbtcp,
                     "port",
                     &cfg.modbus_tcp_port);

        json_get_int(mbtcp,
                     "slave_id",
                     &cfg.modbus_tcp_slave_id);
    }

    /*------------------------------------------------------*/
    /* OTA                                                   */
    /*------------------------------------------------------*/

    char *ota = strstr(json, "\"ota\"");

    if (ota)
    {
        json_get_int(ota,
                     "enable",
                     &cfg.ota_enable);

        json_get_string(ota,
                        "app_topic",
                        cfg.ota_app_topic,
                        sizeof(cfg.ota_app_topic));

        json_get_string(ota,
                        "system_topic",
                        cfg.ota_system_topic,
                        sizeof(cfg.ota_system_topic));

        json_get_string(ota,
                        "status_topic",
                        cfg.ota_status_topic,
                        sizeof(cfg.ota_status_topic));

        json_get_string(ota,
                        "download_dir",
                        cfg.ota_download_dir,
                        sizeof(cfg.ota_download_dir));

        json_get_string(ota,
                        "app_version",
                        cfg.app_version,
                        sizeof(cfg.app_version));

        json_get_string(ota,
                        "app_binary_path",
                        cfg.app_binary_path,
                        sizeof(cfg.app_binary_path));
    }

    free(json);

    printf("\n========== Settings Loaded ==========\n");
    printf("Device ID      : %s\n", cfg.device_id);
    printf("Slave ID       : %d\n", cfg.modbus_slave);
    printf("Baud Rate      : %d\n", cfg.modbus_baud);
    printf("Parity         : %s\n", cfg.modbus_parity);
    printf("Stop Bits      : %d\n", cfg.modbus_stop_bits);
    printf("Port           : %s\n", cfg.modbus_port);
    printf("Interval       : %d sec\n", cfg.interval);

    printf("WiFi SSID      : %s\n", cfg.wifi_ssid);
    printf("WiFi Country   : %s\n", cfg.wifi_country);
    printf("WiFi Enable    : %d\n", cfg.wifi_enable);

    printf("MQTT Broker    : %s\n", cfg.mqtt_broker);
    printf("MQTT Port      : %d\n", cfg.mqtt_port);
    printf("MQTT Client ID : %s\n", cfg.mqtt_client_id);
    printf("MQTT Topic     : %s\n", cfg.mqtt_topic);
    printf("MQTT CA Cert   : %s\n", cfg.mqtt_ca_cert);
    printf("MQTT Dev Cert  : %s\n", cfg.mqtt_device_cert);
    printf("MQTT Key       : %s\n", cfg.mqtt_private_key);

    printf("MB TCP Enable  : %d\n", cfg.modbus_tcp_enable);
    printf("MB TCP IP      : %s\n", cfg.modbus_tcp_ip);
    printf("MB TCP Port    : %d\n", cfg.modbus_tcp_port);
    printf("MB TCP Slave   : %d\n", cfg.modbus_tcp_slave_id);

    printf("OTA Enable     : %d\n", cfg.ota_enable);
    printf("OTA App Topic  : %s\n", cfg.ota_app_topic);
    printf("OTA Sys Topic  : %s\n", cfg.ota_system_topic);
    printf("OTA Status     : %s\n", cfg.ota_status_topic);
    printf("OTA Dir        : %s\n", cfg.ota_download_dir);
    printf("App Version    : %s\n", cfg.app_version);
    printf("App Binary     : %s\n", cfg.app_binary_path);

    printf("=====================================\n\n");

    return 0;
}

/*------------------------------------------------------------*/
/**
 * @brief Reload settings from the JSON configuration file.
 *
 * Re-reads the configuration file. Intended to be called
 * from the SIGHUP handler for hot-reload of credentials
 * and MQTT settings.
 *
 * @return 0 on success
 * @return -1 if JSON file cannot be opened
 */
/*------------------------------------------------------------*/
int settings_reload(void)
{
    printf("[SETTINGS] Reloading configuration...\n");

    return settings_load();
}
