/**
 * @file settings.h
 * @brief Smart RTU application configuration interface.
 *
 * This module loads and manages the Smart RTU configuration from
 * the JSON configuration file generated by the Smart RTU
 * Configuration Tool. Default values are used for any missing
 * configuration parameters.
 */

#ifndef SETTINGS_H
#define SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------- */
/* Configuration File                                                         */
/* -------------------------------------------------------------------------- */

/**
 * @brief Smart RTU configuration file.
 */
#define SETTINGS_FILE "smart_rtu_config.json"

/* -------------------------------------------------------------------------- */
/* Default Modbus RTU Configuration                                           */
/* -------------------------------------------------------------------------- */

/** @brief Default Modbus serial port. */
#define MODBUS_PORT_DEF        "/dev/ttySTM2"

/** @brief Default Modbus baud rate. */
#define MODBUS_BAUD_DEF        9600

/** @brief Default Modbus slave address. */
#define MODBUS_SLAVE_DEF       1

/** @brief Default Modbus parity. */
#define MODBUS_PARITY_DEF      "None"

/** @brief Default Modbus stop bits. */
#define MODBUS_STOPBITS_DEF    1

/* -------------------------------------------------------------------------- */
/* Default Modbus TCP Configuration                                           */
/* -------------------------------------------------------------------------- */

/** @brief Default Modbus TCP enable state (disabled). */
#define MODBUS_TCP_ENABLE_DEF  0

/** @brief Default Modbus TCP slave IP (unconfigured). */
#define MODBUS_TCP_IP_DEF      ""

/** @brief Default Modbus TCP port. */
#define MODBUS_TCP_PORT_DEF    502

/** @brief Default Modbus TCP slave ID. */
#define MODBUS_TCP_SLAVE_DEF   1

/* -------------------------------------------------------------------------- */
/* Default MQTT Configuration (AWS IoT Core)                                  */
/* -------------------------------------------------------------------------- */

/** @brief Default MQTT broker address (unconfigured). */
#define MQTT_BROKER_DEF        ""

/** @brief Default MQTT broker port. */
#define MQTT_PORT_DEF          8883

/** @brief Default MQTT client ID (unconfigured). */
#define MQTT_CLIENT_ID_DEF     ""

/** @brief Default CA certificate path. */
#define MQTT_CA_CERT_DEF       "/etc/ssl/certs/AmazonRootCA1.pem"

/** @brief Default device certificate path. */
#define MQTT_DEVICE_CERT_DEF   "/etc/ssl/certs/device-certificate.pem.crt"

/** @brief Default device private key path. */
#define MQTT_PRIVATE_KEY_DEF   "/etc/ssl/private/device-private.pem.key"

/** @brief Default MQTT publish topic. */
#define MQTT_TOPIC_DEF         "modbus/data"

/* -------------------------------------------------------------------------- */
/* Default OTA Configuration                                                  */
/* -------------------------------------------------------------------------- */

/** @brief Default OTA enable state (disabled). */
#define OTA_ENABLE_DEF         0

/** @brief Default OTA app command topic pattern. */
#define OTA_APP_TOPIC_DEF      "devices/%s/ota/app"

/** @brief Default OTA system command topic pattern. */
#define OTA_SYSTEM_TOPIC_DEF   "devices/%s/ota/system"

/** @brief Default OTA status report topic pattern. */
#define OTA_STATUS_TOPIC_DEF   "devices/%s/ota/status"

/** @brief Default OTA download directory. */
#define OTA_DOWNLOAD_DIR_DEF   "/tmp/ota"

/** @brief Default application version string. */
#define APP_VERSION_DEF        "1.0.0"

/** @brief Default application binary path on board. */
#define APP_BINARY_PATH_DEF    "/home/root/edb_c/linking/main"

/* -------------------------------------------------------------------------- */
/* Default Polling Configuration                                              */
/* -------------------------------------------------------------------------- */

/** @brief Default Modbus polling interval (seconds). */
#define INTERVAL_DEF           30

/* -------------------------------------------------------------------------- */
/* Default Wi-Fi Configuration                                                */
/* -------------------------------------------------------------------------- */

/** @brief Default Wi-Fi enabled state. */
#define WIFI_ENABLE_DEF        1

/** @brief Default Wi-Fi SSID. */
#define WIFI_SSID_DEF          "Amset"

/** @brief Default Wi-Fi password. */
#define WIFI_PASSWORD_DEF      "Amset@123"

/** @brief Default Wi-Fi country code. */
#define WIFI_COUNTRY_DEF       "IN"

/* -------------------------------------------------------------------------- */
/* Data Types                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * @brief Application configuration.
 *
 * Stores all runtime configuration loaded from the JSON
 * configuration file.
 */
typedef struct
{
    /* Device */

    /** @brief Device identifier. */
    char device_id[64];

    /* Modbus RTU */

    /** @brief Modbus serial port. */
    char modbus_port[64];

    /** @brief Modbus baud rate. */
    int modbus_baud;

    /** @brief Modbus slave address. */
    int modbus_slave;

    /** @brief Modbus parity setting. */
    char modbus_parity[16];

    /** @brief Modbus stop bits. */
    int modbus_stop_bits;

    /* Modbus TCP */

    /** @brief Modbus TCP enable flag. */
    int modbus_tcp_enable;

    /** @brief Modbus TCP slave IP address. */
    char modbus_tcp_ip[64];

    /** @brief Modbus TCP port number. */
    int modbus_tcp_port;

    /** @brief Modbus TCP slave ID. */
    int modbus_tcp_slave_id;

    /* MQTT (AWS IoT Core) */

    /** @brief MQTT broker hostname. */
    char mqtt_broker[256];

    /** @brief MQTT broker port. */
    int mqtt_port;

    /** @brief MQTT client ID (AWS IoT thing name). */
    char mqtt_client_id[128];

    /** @brief Path to CA certificate (AmazonRootCA1.pem). */
    char mqtt_ca_cert[256];

    /** @brief Path to device certificate. */
    char mqtt_device_cert[256];

    /** @brief Path to device private key. */
    char mqtt_private_key[256];

    /** @brief MQTT publish topic. */
    char mqtt_topic[128];

    /* Polling */

    /** @brief Modbus polling interval in seconds. */
    int interval;

    /* Wi-Fi */

    /** @brief Wi-Fi enabled flag. */
    int wifi_enable;

    /** @brief Wi-Fi SSID. */
    char wifi_ssid[64];

    /** @brief Wi-Fi password. */
    char wifi_password[64];

    /** @brief Wi-Fi country code. */
    char wifi_country[8];

    /* OTA */

    /** @brief OTA enable flag. */
    int ota_enable;

    /** @brief MQTT topic for app OTA commands. */
    char ota_app_topic[128];

    /** @brief MQTT topic for system OTA commands. */
    char ota_system_topic[128];

    /** @brief MQTT topic for OTA status reports. */
    char ota_status_topic[128];

    /** @brief Directory for OTA downloads. */
    char ota_download_dir[256];

    /** @brief Current application version. */
    char app_version[32];

    /** @brief Path to the application binary on the board. */
    char app_binary_path[256];

} AppSettings;

/* -------------------------------------------------------------------------- */
/* Global Variables                                                           */
/* -------------------------------------------------------------------------- */

/**
 * @brief Global application configuration.
 *
 * Contains the currently active configuration loaded from
 * the JSON configuration file.
 */
extern AppSettings cfg;

/* -------------------------------------------------------------------------- */
/* API                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * @brief Loads the factory default configuration.
 *
 * Initializes the global configuration structure with
 * built-in default values.
 */
void settings_defaults(void);

/**
 * @brief Loads the application configuration.
 *
 * Reads the configuration from ::SETTINGS_FILE.
 * Any missing configuration fields retain their
 * default values.
 *
 * @return
 * - 0 on success.
 * - -1 if the configuration file cannot be loaded.
 */
int settings_load(void);

/**
 * @brief Reloads the application configuration.
 *
 * Re-reads the configuration from ::SETTINGS_FILE.
 * Used by the SIGHUP handler for hot-reload.
 *
 * @return
 * - 0 on success.
 * - -1 if the configuration file cannot be loaded.
 */
int settings_reload(void);

/* -------------------------------------------------------------------------- */
/* Convenience Getters                                                        */
/* -------------------------------------------------------------------------- */

/**
 * @brief Returns the configured Wi-Fi SSID.
 *
 * @return Pointer to the Wi-Fi SSID string.
 */
static inline const char *settings_get_ssid(void)
{
    return cfg.wifi_ssid;
}

/**
 * @brief Returns the configured Wi-Fi password.
 *
 * @return Pointer to the Wi-Fi password string.
 */
static inline const char *settings_get_password(void)
{
    return cfg.wifi_password;
}

/**
 * @brief Returns the configured Modbus slave address.
 *
 * @return Modbus slave ID.
 */
static inline int settings_get_slave(void)
{
    return cfg.modbus_slave;
}

/**
 * @brief Returns the configured Modbus baud rate.
 *
 * @return Modbus baud rate.
 */
static inline int settings_get_baud(void)
{
    return cfg.modbus_baud;
}

/**
 * @brief Returns the configured polling interval.
 *
 * @return Polling interval in seconds.
 */
static inline int settings_get_interval(void)
{
    return cfg.interval;
}

#ifdef __cplusplus
}
#endif

#endif /* SETTINGS_H */
