/**
 * @file settings.h
 * @brief Smart RTU configuration loader.
 *
 * Loads Smart RTU configuration from
 * smart_rtu_config.json generated by the
 * Smart RTU Configuration Tool.
 */

#ifndef SETTINGS_H
#define SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

/*-----------------------------------------------------------
 * Configuration file
 *----------------------------------------------------------*/

#define SETTINGS_FILE "smart_rtu_config.json"

/*-----------------------------------------------------------
 * Default Modbus settings
 *----------------------------------------------------------*/

#define MODBUS_PORT_DEF        "/dev/ttyACM0"
#define MODBUS_BAUD_DEF        9600
#define MODBUS_SLAVE_DEF       1
#define MODBUS_PARITY_DEF      "None"
#define MODBUS_STOPBITS_DEF    1

/*-----------------------------------------------------------
 * Default MQTT settings
 *----------------------------------------------------------*/

#define MQTT_BROKER_DEF        "25d1470809e1409796c6dd8bd937c33c.s1.eu.hivemq.cloud"
#define MQTT_PORT_DEF          8883
#define MQTT_USERNAME_DEF      "Aishwarya"
#define MQTT_PASSWORD_DEF      "password"

/*-----------------------------------------------------------
 * Default polling interval
 *----------------------------------------------------------*/

#define INTERVAL_DEF           30

/*-----------------------------------------------------------
 * Default WiFi settings
 *----------------------------------------------------------*/

#define WIFI_ENABLE_DEF        1
#define WIFI_SSID_DEF          "redmi"
#define WIFI_PASSWORD_DEF      "1234567890"
#define WIFI_COUNTRY_DEF       "IN"

/*-----------------------------------------------------------
 * Application configuration structure
 *----------------------------------------------------------*/

/**
 * @brief Complete application configuration.
 */
typedef struct
{
    /*================ Device =================*/

    char device_id[64];

    /*================ Modbus ================*/

    char modbus_port[64];

    int  modbus_baud;

    int  modbus_slave;

    char modbus_parity[16];

    int  modbus_stop_bits;

    /*================ MQTT ==================*/

    char mqtt_broker[256];

    int  mqtt_port;

    char mqtt_user[64];

    char mqtt_pass[64];

    /*================ Scan ==================*/

    int interval;

    /*================ WiFi ==================*/

    int  wifi_enable;

    char wifi_ssid[64];

    char wifi_password[64];

    char wifi_country[8];

} AppSettings;

/**
 * @brief Global configuration object.
 */
extern AppSettings cfg;

/*-----------------------------------------------------------
 * Public API
 *----------------------------------------------------------*/

/**
 * @brief Load factory default settings.
 */


void settings_defaults(void);

/**
 * @brief Load configuration from smart_rtu_config.json.
 *
 * Missing fields retain their default values.
 *
 * @return 0 on success
 * @return -1 if file could not be loaded
 */
int settings_load(void);

/*-----------------------------------------------------------
 * Convenience getters
 *----------------------------------------------------------*/

/**
 * @brief Get configured WiFi SSID.
 */
static inline const char *settings_get_ssid(void)
{
    return cfg.wifi_ssid;
}

/**
 * @brief Get configured WiFi password.
 */
static inline const char *settings_get_password(void)
{
    return cfg.wifi_password;
}

/**
 * @brief Get configured Modbus slave ID.
 */
static inline int settings_get_slave(void)
{
    return cfg.modbus_slave;
}

/**
 * @brief Get configured Modbus baud rate.
 */
static inline int settings_get_baud(void)
{
    return cfg.modbus_baud;
}

/**
 * @brief Get configured polling interval.
 */
static inline int settings_get_interval(void)
{
    return cfg.interval;
}

#ifdef __cplusplus
}
#endif

#endif /* SETTINGS_H */