/**
 * @file settings.h
 * @brief Smart RTU application configuration interface.
 *
 * This module loads and manages the Smart RTU configuration from
 * the JSON configuration file generated by the Smart RTU
 * Configuration Tool. Default values are used for any missing
 * configuration parameters.
 */

#ifndef SETTINGS_H
#define SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------------------------- */
/* Configuration File                                                         */
/* -------------------------------------------------------------------------- */

/**
 * @brief Smart RTU configuration file.
 */
#define SETTINGS_FILE "smart_rtu_config.json"

/* -------------------------------------------------------------------------- */
/* Default Modbus Configuration                                               */
/* -------------------------------------------------------------------------- */

/** @brief Default Modbus serial port. */
#define MODBUS_PORT_DEF        "/dev/ttySTM2"

/** @brief Default Modbus baud rate. */
#define MODBUS_BAUD_DEF        9600

/** @brief Default Modbus slave address. */
#define MODBUS_SLAVE_DEF       1

/** @brief Default Modbus parity. */
#define MODBUS_PARITY_DEF      "None"

/** @brief Default Modbus stop bits. */
#define MODBUS_STOPBITS_DEF    1

/* -------------------------------------------------------------------------- */
/* Default MQTT Configuration                                                 */
/* -------------------------------------------------------------------------- */

/** @brief Default MQTT broker address. */
#define MQTT_BROKER_DEF        "25d1470809e1409796c6dd8bd937c33c.s1.eu.hivemq.cloud"

/** @brief Default MQTT broker port. */
#define MQTT_PORT_DEF          8883

/** @brief Default MQTT username. */
#define MQTT_USERNAME_DEF      "Aishwarya"

/** @brief Default MQTT password. */
#define MQTT_PASSWORD_DEF      "password"

/* -------------------------------------------------------------------------- */
/* Default Polling Configuration                                              */
/* -------------------------------------------------------------------------- */

/** @brief Default Modbus polling interval (seconds). */
#define INTERVAL_DEF           30

/* -------------------------------------------------------------------------- */
/* Default Wi-Fi Configuration                                                */
/* -------------------------------------------------------------------------- */

/** @brief Default Wi-Fi enabled state. */
#define WIFI_ENABLE_DEF        1

/** @brief Default Wi-Fi SSID. */
#define WIFI_SSID_DEF          "Amset"

/** @brief Default Wi-Fi password. */
#define WIFI_PASSWORD_DEF      "Amset@123"

/** @brief Default Wi-Fi country code. */
#define WIFI_COUNTRY_DEF       "IN"

/* -------------------------------------------------------------------------- */
/* Data Types                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * @brief Application configuration.
 *
 * Stores all runtime configuration loaded from the JSON
 * configuration file.
 */
typedef struct
{
    /* Device */

    /** @brief Device identifier. */
    char device_id[64];

    /* Modbus */

    /** @brief Modbus serial port. */
    char modbus_port[64];

    /** @brief Modbus baud rate. */
    int modbus_baud;

    /** @brief Modbus slave address. */
    int modbus_slave;

    /** @brief Modbus parity setting. */
    char modbus_parity[16];

    /** @brief Modbus stop bits. */
    int modbus_stop_bits;

    /* MQTT */

    /** @brief MQTT broker hostname. */
    char mqtt_broker[256];

    /** @brief MQTT broker port. */
    int mqtt_port;

    /** @brief MQTT username. */
    char mqtt_user[64];

    /** @brief MQTT password. */
    char mqtt_pass[64];

    /* Polling */

    /** @brief Modbus polling interval in seconds. */
    int interval;

    /* Wi-Fi */

    /** @brief Wi-Fi enabled flag. */
    int wifi_enable;

    /** @brief Wi-Fi SSID. */
    char wifi_ssid[64];

    /** @brief Wi-Fi password. */
    char wifi_password[64];

    /** @brief Wi-Fi country code. */
    char wifi_country[8];

} AppSettings;

/* -------------------------------------------------------------------------- */
/* Global Variables                                                           */
/* -------------------------------------------------------------------------- */

/**
 * @brief Global application configuration.
 *
 * Contains the currently active configuration loaded from
 * the JSON configuration file.
 */
extern AppSettings cfg;

/* -------------------------------------------------------------------------- */
/* API                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * @brief Loads the factory default configuration.
 *
 * Initializes the global configuration structure with
 * built-in default values.
 */
void settings_defaults(void);

/**
 * @brief Loads the application configuration.
 *
 * Reads the configuration from ::SETTINGS_FILE.
 * Any missing configuration fields retain their
 * default values.
 *
 * @return
 * - 0 on success.
 * - -1 if the configuration file cannot be loaded.
 */
int settings_load(void);

/* -------------------------------------------------------------------------- */
/* Convenience Getters                                                        */
/* -------------------------------------------------------------------------- */

/**
 * @brief Returns the configured Wi-Fi SSID.
 *
 * @return Pointer to the Wi-Fi SSID string.
 */
static inline const char *settings_get_ssid(void)
{
    return cfg.wifi_ssid;
}

/**
 * @brief Returns the configured Wi-Fi password.
 *
 * @return Pointer to the Wi-Fi password string.
 */
static inline const char *settings_get_password(void)
{
    return cfg.wifi_password;
}

/**
 * @brief Returns the configured Modbus slave address.
 *
 * @return Modbus slave ID.
 */
static inline int settings_get_slave(void)
{
    return cfg.modbus_slave;
}

/**
 * @brief Returns the configured Modbus baud rate.
 *
 * @return Modbus baud rate.
 */
static inline int settings_get_baud(void)
{
    return cfg.modbus_baud;
}

/**
 * @brief Returns the configured polling interval.
 *
 * @return Polling interval in seconds.
 */
static inline int settings_get_interval(void)
{
    return cfg.interval;
}

#ifdef __cplusplus
}
#endif

#endif /* SETTINGS_H */