/**
 * @file settings.c
 * @brief Loads Smart RTU configuration from smart_rtu_config.json.
 *
 * Reads the JSON configuration generated by the Smart RTU Tool and
 * populates the global AppSettings structure used throughout the
 * application.
 */

#include "settings.h"
#include "json.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

AppSettings cfg;

/*------------------------------------------------------------*/
/**
 * @brief Load default configuration values.
 *
 * These values are used whenever a field is missing from the
 * JSON configuration file.
 */
/*------------------------------------------------------------*/
void settings_defaults(void)
{
    /* Device */

    strcpy(cfg.device_id, "AMSET-001");

    /* Modbus */

    strcpy(cfg.modbus_port, MODBUS_PORT_DEF);
    cfg.modbus_baud = MODBUS_BAUD_DEF;
    cfg.modbus_slave = MODBUS_SLAVE_DEF;
    strcpy(cfg.modbus_parity, MODBUS_PARITY_DEF);
    cfg.modbus_stop_bits = MODBUS_STOPBITS_DEF;

    /* MQTT */

    strcpy(cfg.mqtt_broker, MQTT_BROKER_DEF);
    cfg.mqtt_port = MQTT_PORT_DEF;
    strcpy(cfg.mqtt_user, MQTT_USERNAME_DEF);
    strcpy(cfg.mqtt_pass, MQTT_PASSWORD_DEF);

    /* Scan interval */

    cfg.interval = INTERVAL_DEF;

    /* WiFi */

    cfg.wifi_enable = WIFI_ENABLE_DEF;
    strcpy(cfg.wifi_ssid, WIFI_SSID_DEF);
    strcpy(cfg.wifi_password, WIFI_PASSWORD_DEF);
    strcpy(cfg.wifi_country, WIFI_COUNTRY_DEF);
}

/*------------------------------------------------------------*/
/**
 * @brief Load settings from Smart RTU JSON file.
 *
 * Reads:
 *   - device
 *   - wifi
 *   - mqtt (optional)
 *
 * Missing fields retain their default values.
 *
 * @return 0 on success
 * @return -1 if JSON file cannot be opened
 */
/*------------------------------------------------------------*/
int settings_load(void)
{
    settings_defaults();

    char *json = read_file(SETTINGS_FILE);

    if (json == NULL)
    {
        printf("[SETTINGS] %s not found. Using defaults.\n",
               SETTINGS_FILE);
        return -1;
    }

    /*------------------------------------------------------*/
    /* Device                                                */
    /*------------------------------------------------------*/

    char *device = strstr(json, "\"device\"");

    if (device)
    {
        json_get_string(device,
                        "device_id",
                        cfg.device_id,
                        sizeof(cfg.device_id));

        json_get_int(device,
                     "slave_id",
                     &cfg.modbus_slave);

        json_get_int(device,
                     "baud",
                     &cfg.modbus_baud);

        json_get_int(device,
                     "interval_sec",
                     &cfg.interval);

        json_get_string(device,
                        "parity",
                        cfg.modbus_parity,
                        sizeof(cfg.modbus_parity));

        json_get_int(device,
                     "stop_bits",
                     &cfg.modbus_stop_bits);
    }

    /*------------------------------------------------------*/
    /* WiFi                                                  */
    /*------------------------------------------------------*/

    char *wifi = strstr(json, "\"wifi\"");

    if (wifi)
    {
        json_get_string(wifi,
                        "ssid",
                        cfg.wifi_ssid,
                        sizeof(cfg.wifi_ssid));

        json_get_string(wifi,
                        "password",
                        cfg.wifi_password,
                        sizeof(cfg.wifi_password));

        json_get_string(wifi,
                        "country",
                        cfg.wifi_country,
                        sizeof(cfg.wifi_country));

        json_get_int(wifi,
                     "enable",
                     &cfg.wifi_enable);
    }

    /*------------------------------------------------------*/
    /* MQTT (optional)                                       */
    /*------------------------------------------------------*/

    char *mqtt = strstr(json, "\"mqtt\"");

    if (mqtt)
    {
        json_get_string(mqtt,
                        "broker",
                        cfg.mqtt_broker,
                        sizeof(cfg.mqtt_broker));

        json_get_int(mqtt,
                     "port",
                     &cfg.mqtt_port);

        json_get_string(mqtt,
                        "username",
                        cfg.mqtt_user,
                        sizeof(cfg.mqtt_user));

        json_get_string(mqtt,
                        "password",
                        cfg.mqtt_pass,
                        sizeof(cfg.mqtt_pass));
    }

    free(json);

    printf("\n========== Settings Loaded ==========\n");
    printf("Device ID      : %s\n", cfg.device_id);
    printf("Slave ID       : %d\n", cfg.modbus_slave);
    printf("Baud Rate      : %d\n", cfg.modbus_baud);
    printf("Parity         : %s\n", cfg.modbus_parity);
    printf("Stop Bits      : %d\n", cfg.modbus_stop_bits);
    printf("Port           : %s\n", cfg.modbus_port);
    printf("Interval       : %d sec\n", cfg.interval);

    printf("WiFi SSID      : %s\n", cfg.wifi_ssid);
    printf("WiFi Country   : %s\n", cfg.wifi_country);
    printf("WiFi Enable    : %d\n", cfg.wifi_enable);

    printf("MQTT Broker    : %s\n", cfg.mqtt_broker);
    printf("MQTT Port      : %d\n", cfg.mqtt_port);

    printf("=====================================\n\n");

    return 0;
}